### ISSUE TITLE
Memmap issues (stivale)

### ISSUE THREAD

**Issue by N00byEdge** [TomatOrg/TomatBoot-UEFI#11]
Currently, tomatboot is passing stivale structures to the loaded kernel and putting page tables at addresses above the 1MB mark. The ranges below 1MB is reserved for the bootloader to use for these structures. This causes issues when trying to use memory beyond 1MB, as you collide with the memory map, module strucures, page tables etc, even though they are marked as available in the memory map.

This issue could be resolved by moving page tables and stivale related structures to below the 1M mark, probably easiest with a trivial bump allocator.

**Comment by Itay2805** [comment]
Indeed it is an issue. 

Just to expand a bit for future viewer, the page table in uefi is marked as boot services memory and is marked as readonly in the memory map (mainly to avoid corrupting the tables), since boot services memory is marked as free in the memory map passed to the kernel it could try and use them.

All we need is to move from reusing the existing uefi tables to allocating it below 1mb (AllocatePages can do that), while at it we can convert all the structures which are allocated as reserved currently to also be allocated bellow 1mb and be marked as free for the kernel.

**Comment by Itay2805** [comment]
This should be fixed since now we map the `EfiBootServicesCode` & `EfiBootServicesData` as `STIVALE_BOOTLODAER_RECLAIM`, which means it should not be used until the bootloader is no longer needed :)
